version: '3.8'

services:
  name-matching-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production
      - TOKENIZERS_PARALLELISM=false
      - OMP_NUM_THREADS=1
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s